{"name": "Если отправить запрос на удаление курьера без id, запрос вернет код ошибки 400", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код в ответе: ожидался 400, получен \"404\", ответ: \"{\"code\":404,\"message\":\"Not Found.\"}\"", "trace": "self = <test_delete_courier.TestDeleteCourier object at 0x000002BE11744F10>, register_new_courier = 240146\n\n    @allure.title('Если отправить запрос на удаление курьера без id, запрос вернет код ошибки 400')\n    def test_delete_courier_missing_id_error_code(self, register_new_courier):\n        # задаем пустой user_id\n        user_id = \"\"\n        # направляем запрос на удаление курьера с пустым id\n        response = delete_courier(user_id)\n        # проверяем что получен код ответа 400\n>       check_status_code(response, code.BAD_REQUEST)\n\ntests\\test_delete_courier.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [404]>, expected_code = 400\n\n    @allure.step('Проверяем код ответа')\n    def check_status_code(response, expected_code):\n        # проверяем что получен код ответа expected_code\n        received_code = response.status_code\n>       assert received_code == expected_code, f'Неверный код в ответе: ожидался {expected_code}, получен \"{received_code}\", ответ: \"{response.text}\"'\nE       AssertionError: Неверный код в ответе: ожидался 400, получен \"404\", ответ: \"{\"code\":404,\"message\":\"Not Found.\"}\"\n\nhelpers\\helpers_on_check_response.py:12: AssertionError"}, "steps": [{"name": "Отправляем API-запрос на удаление курьера", "status": "passed", "parameters": [{"name": "user_id", "value": "''"}], "start": 1701712218753, "stop": 1701712218807}, {"name": "Проверяем код ответа", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код в ответе: ожидался 400, получен \"404\", ответ: \"{\"code\":404,\"message\":\"Not Found.\"}\"\n", "trace": "  File \"C:\\Python_projects\\Python_QA\\qa_python_1\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Python_projects\\Python_QA\\qa_python_7\\helpers\\helpers_on_check_response.py\", line 12, in check_status_code\n    assert received_code == expected_code, f'Неверный код в ответе: ожидался {expected_code}, получен \"{received_code}\", ответ: \"{response.text}\"'\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "response", "value": "<Response [404]>"}, {"name": "expected_code", "value": "400"}], "start": 1701712218808, "stop": 1701712218808}], "attachments": [{"name": "stdout", "source": "25b992be-13c9-4e71-9c6e-49ea6b8a4b4e-attachment.txt", "type": "text/plain"}], "start": 1701712218753, "stop": 1701712218809, "uuid": "b5a6db9e-1172-47bf-a6a0-202af5a6775e", "historyId": "e001a9ec9abc92215fab0936d953945d", "testCaseId": "e001a9ec9abc92215fab0936d953945d", "fullName": "tests.test_delete_courier.TestDeleteCourier#test_delete_courier_missing_id_error_code", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('register_new_courier')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_delete_courier"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "DESKTOP-O6MNHQN"}, {"name": "thread", "value": "9112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_delete_courier"}]}