{"name": "Проверяем, что нельзя создать двух одинаковых курьеров и запрос возвращает код ошибки 409", "status": "failed", "statusDetails": {"message": "AssertionError: Получено неверное сообщение: ожидалось: \"Этот логин уже используется\", получено: \"Этот логин уже используется. Попробуйте другой.\"", "trace": "self = <test_create_courier.TestCreateCourier object at 0x000002BE11738CD0>\ncreate_new_courier = {'firstName': 'rclihpahos', 'login': 'kiihptaulj', 'password': 'mdyunrtmbm'}\n\n    @allure.title('Проверяем, что нельзя создать двух одинаковых курьеров и запрос возвращает код ошибки 409')\n    def test_create_courier_double_courier_not_created(self, create_new_courier):\n        # создаем нового курьера и получаем его данные\n        user_data = create_new_courier\n        # делаем повторную попытку зарегистрировать курьера с теми же данными\n        response = create_courier(user_data)\n        # проверяем что получен код ответа 409\n        check_status_code(response, code.CONFLICT)\n        # проверяем сообщение об ошибке\n>       check_message(response, text.LOGIN_ALREADY_USED_TEXT)\n\ntests\\test_create_courier.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [409]>, expected_message = 'Этот логин уже используется'\n\n    @allure.step('Проверяем сообщение в ответе')\n    def check_message(response, expected_message):\n        # проверяем что в ответе есть message\n        received_text = response.text\n        received_body = response.json()\n        assert KEYS.MESSAGE_KEY in received_body, f'В ответе отсутствует ключ \"{KEYS.MESSAGE_KEY}\", текст: \"{received_text}\"'\n        # проверяем сообщение об ошибке\n        received_message = received_body[KEYS.MESSAGE_KEY]\n>       assert received_message == expected_message, f'Получено неверное сообщение: ожидалось: \"{expected_message}\", получено: \"{received_message}\"'\nE       AssertionError: Получено неверное сообщение: ожидалось: \"Этот логин уже используется\", получено: \"Этот логин уже используется. Попробуйте другой.\"\n\nhelpers\\helpers_on_check_response.py:23: AssertionError"}, "steps": [{"name": "Отправляем API-запрос на создание нового курьера", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'kiihptaulj', 'password': 'mdyunrtmbm', 'firstName': 'rclihpahos'}"}], "start": 1701712217350, "stop": 1701712217431}, {"name": "Проверяем код ответа", "status": "passed", "parameters": [{"name": "response", "value": "<Response [409]>"}, {"name": "expected_code", "value": "409"}], "start": 1701712217432, "stop": 1701712217432}, {"name": "Проверяем сообщение в ответе", "status": "failed", "statusDetails": {"message": "AssertionError: Получено неверное сообщение: ожидалось: \"Этот логин уже используется\", получено: \"Этот логин уже используется. Попробуйте другой.\"\n", "trace": "  File \"C:\\Python_projects\\Python_QA\\qa_python_1\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Python_projects\\Python_QA\\qa_python_7\\helpers\\helpers_on_check_response.py\", line 23, in check_message\n    assert received_message == expected_message, f'Получено неверное сообщение: ожидалось: \"{expected_message}\", получено: \"{received_message}\"'\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "response", "value": "<Response [409]>"}, {"name": "expected_message", "value": "'Этот логин уже используется'"}], "start": 1701712217432, "stop": 1701712217432}], "attachments": [{"name": "stdout", "source": "3c8c9974-2365-48b2-9cd8-6680dd834daf-attachment.txt", "type": "text/plain"}], "start": 1701712217349, "stop": 1701712217433, "uuid": "80a86a81-1750-4b73-b126-cbd0be7da88e", "historyId": "91c1793c93d2d177e834e7228a8ef3be", "testCaseId": "91c1793c93d2d177e834e7228a8ef3be", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_courier_double_courier_not_created", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('create_new_courier')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "DESKTOP-O6MNHQN"}, {"name": "thread", "value": "9112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}