{"name": "Проверяем получение заказа по его трек-номеру: запрос с несуществующим номером заказа возвращает ошибку", "status": "failed", "statusDetails": {"message": "AssertionError: Получено неверное сообщение: ожидалось: \"Заказ не найден\", получено: \"Not Found.\"", "trace": "self = <test_get_order.TestGetOrder object at 0x000002BE11747990>, register_new_courier = 240152, create_order = 444681\n\n    @allure.title('Проверяем получение заказа по его трек-номеру: запрос с несуществующим номером заказа возвращает ошибку')\n    def test_get_order_invalid_track(self, register_new_courier, create_order):\n        # создаем и регистрируем нового курьера и получаем его данные\n        user_id = register_new_courier\n        # создаем новый заказ, проверяем код ответа и получаем номер заказа\n        track = create_order\n        # направляем запрос получить заказ по его треку (номеру) с несуществующим номером трека \"0\"\n        response = get_order_by_param(\"0\")\n        # проверяем что получен код ответа 404\n        check_status_code(response, code.NOT_FOUND)\n        # проверяем сообщение об ошибке\n>       check_message(response, text.GET_ORDER_NOT_FOUND)\n\ntests\\test_get_order.py:53: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [404]>, expected_message = 'Заказ не найден'\n\n    @allure.step('Проверяем сообщение в ответе')\n    def check_message(response, expected_message):\n        # проверяем что в ответе есть message\n        received_text = response.text\n        received_body = response.json()\n        assert KEYS.MESSAGE_KEY in received_body, f'В ответе отсутствует ключ \"{KEYS.MESSAGE_KEY}\", текст: \"{received_text}\"'\n        # проверяем сообщение об ошибке\n        received_message = received_body[KEYS.MESSAGE_KEY]\n>       assert received_message == expected_message, f'Получено неверное сообщение: ожидалось: \"{expected_message}\", получено: \"{received_message}\"'\nE       AssertionError: Получено неверное сообщение: ожидалось: \"Заказ не найден\", получено: \"Not Found.\"\n\nhelpers\\helpers_on_check_response.py:23: AssertionError"}, "steps": [{"name": "Отправляем API-запрос на получение заказа по его трек-номеру", "status": "passed", "parameters": [{"name": "param", "value": "'0'"}], "start": 1701712221109, "stop": 1701712221152}, {"name": "Проверяем код ответа", "status": "passed", "parameters": [{"name": "response", "value": "<Response [404]>"}, {"name": "expected_code", "value": "404"}], "start": 1701712221153, "stop": 1701712221153}, {"name": "Проверяем сообщение в ответе", "status": "failed", "statusDetails": {"message": "AssertionError: Получено неверное сообщение: ожидалось: \"Заказ не найден\", получено: \"Not Found.\"\n", "trace": "  File \"C:\\Python_projects\\Python_QA\\qa_python_1\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Python_projects\\Python_QA\\qa_python_7\\helpers\\helpers_on_check_response.py\", line 23, in check_message\n    assert received_message == expected_message, f'Получено неверное сообщение: ожидалось: \"{expected_message}\", получено: \"{received_message}\"'\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "response", "value": "<Response [404]>"}, {"name": "expected_message", "value": "'Заказ не найден'"}], "start": 1701712221153, "stop": 1701712221153}], "attachments": [{"name": "stdout", "source": "ae4edc89-2194-401c-ae76-23476f6db36e-attachment.txt", "type": "text/plain"}], "start": 1701712221108, "stop": 1701712221156, "uuid": "9bd706ef-f77b-4f97-b42a-3d92535de0dc", "historyId": "83c67613868e109827ddab790834ce66", "testCaseId": "83c67613868e109827ddab790834ce66", "fullName": "tests.test_get_order.TestGetOrder#test_get_order_invalid_track", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "DESKTOP-O6MNHQN"}, {"name": "thread", "value": "9112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}